Revert "[Dynamo] Simplify DunderDictVariable impl. (#177658)"
This reverts commit ad5a6f6546ed8aa800022324ebede81a1cf0a2a2.

Reverted https://github.com/pytorch/pytorch/pull/177658 on behalf of https://github.com/georgehong due to Revert this stack due to observing first-time test breakages: FAILED CONSISTENTLY: test/test_multiprocessing_spawn.py::ParallelForkServerShouldWorkTest::test_terminate_signal -- torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__' ([comment](https://github.com/pytorch/pytorch/pull/176773#issuecomment-4128280508))