Revert "Implement MKLGenerator  (#151218)"
This reverts commit ab578a9bee3350a9262cc34b1a52e7df175aeccd.

Reverted https://github.com/pytorch/pytorch/pull/151218 on behalf of https://github.com/yangw-dev due to sorry, it breaks internal test. error:fbcode/caffe2/aten/src/ATen/CPUGeneratorImpl.cpp:8:10: fatal error: 'ATen/mklrng/MKLGeneratorImpl.h' file not found ([comment](https://github.com/pytorch/pytorch/pull/151218#issuecomment-3761997088))