Revert "[DTensor] compute shape and offset for arbitrary _StridedShard (#168146)"
This reverts commit 82e93782519e49f07ac363e3509687029c602838.

Reverted https://github.com/pytorch/pytorch/pull/168146 on behalf of https://github.com/yangw-dev due to failed internal tests  due to AttributeError: 'LocalIntNode' object has no attribute 'int_', please fix it and re-merge again ([comment](https://github.com/pytorch/pytorch/pull/168146#issuecomment-3571957707))