Revert "[Dynamo] Represent `__dict__` as `DunderDictVt` in `NNModuleVariable` (#177808)"
This reverts commit d276b28249f91867ca679361101e2f7a2defb957.

Reverted https://github.com/pytorch/pytorch/pull/177808 on behalf of https://github.com/georgehong due to Revert this stack due to observing first-time test breakages: FAILED CONSISTENTLY: test/test_multiprocessing_spawn.py::ParallelForkServerShouldWorkTest::test_terminate_signal -- torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__' ([comment](https://github.com/pytorch/pytorch/pull/176773#issuecomment-4128280508))