[ROCm][CI] fix batch_norm decomp for negative running_var (#177665)
Fixes #168755

All tests performed on an MI300X machine with ROCm version 7.2.26015.

### Before fix:
```
$ PYTHONWARNINGS="ignore" PYTORCH_PRINT_REPRO_ON_FAILURE=0 PYTORCH_TEST_WITH_ROCM=1 python test/test_jit_fuser_te.py TestTEFuserStatic.test_batch_norm
monkeytype is not installed. Skipping tests for Profile-Directed Typing
F
======================================================================
FAIL: test_batch_norm (__main__.TestTEFuserStatic.test_batch_norm)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_internal/common_utils.py", line 1766, in wrapper
    fn(*args, **kwargs)
  File "/var/lib/jenkins/pytorch/test/test_jit_fuser_te.py", line 2434, in test_batch_norm
    test(fn, (i, x))
  File "/var/lib/jenkins/pytorch/test/test_jit_fuser_te.py", line 2416, in test
    torch.testing.assert_close(fn(*args), trace(*args), equal_nan=True)
  File "/opt/conda/envs/py_3.12/lib/python3.12/site-packages/torch/testing/_comparison.py", line 1600, in assert_close
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 25600 / 81920 (31.2%)
Greatest absolute difference: nan at index (0, 2, 0, 0) (up to 1e-05 allowed)
Greatest relative difference: nan at index (0, 2, 0, 0) (up to 1.3e-06 allowed)

----------------------------------------------------------------------
Ran 1 test in 13.574s

FAILED (failures=1)
```

### Experiments:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<!--StartFragment-->

<div style='direction:ltr'>

Test | NaN in Eager mode | NaN in JIT trace   mode | Mismatches   between eager and JIT trace
-- | -- | -- | --
Bn | False | False | 0
ReLU | False | False | 0
Bn + ReLU | False | True | 35,840

</div>

<!--EndFragment-->
</body>

</html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<!--StartFragment-->

<div style='direction:ltr'>

Test | NaN in JIT trace   mode
-- | --
Bn + ReLU   (compiler fusion disabled) | False
Bn + ReLU   (compiler fusion enabled) | True

</div>

<!--EndFragment-->
</body>

</html>

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<!--StartFragment-->

<div style='direction:ltr'>

Test | NaN
-- | --
Bn (with negative   running_var) + ReLU (compiler fusion enabled) | True
Bn (with positive   running_var) + ReLU (compiler fusion enabled) | False

</div>

<!--EndFragment-->
</body>

</html>

Root cause: for this test, running_var is initialized via torch.randn, causing there to be negative values. In Torch Jit trace mode, for Bn + ReLU fusion, incorrect handling of these negative values in running_var leads to sqrt of negative numbers, which results in imaginary numbers or NaNs.

### The fix:
-- modify batch_norm decomposition to handle erroneous negative running_var
-- modify the test so running_var is non-negative (negative variance is mathematically invalid)

### After fix:

```
$ PYTHONWARNINGS="ignore" PYTORCH_PRINT_REPRO_ON_FAILURE=0 PYTORCH_TEST_WITH_ROCM=1 python test/test_jit_fuser_te.py TestTEFuserStatic.test_batch_norm
monkeytype is not installed. Skipping tests for Profile-Directed Typing
.
----------------------------------------------------------------------
Ran 1 test in 14.185s

OK
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/177665
Approved by: https://github.com/jeffdaily