fix: ensure dataclasses with uninitialized fields can be deserialized (#179511)
Fixes an issue in guard serialization that would cause dataclass fields set to `init=False` to get serialized. Upon loading objects like `DefaultsSource`, it would receive the error

```
    restored = pickle.loads(pickle.dumps(source))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DefaultsSource.__init__() takes from 3 to 4 positional arguments but 6 were given
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/179511
Approved by: https://github.com/anijain2305