Fix test_exclude_padding on H100 GPUs (#169177)
The test relies on compute-bound MM ops.
For H100 we get:
`arithmetic_intensity(25) = 8.333333333333334` and `machine_balance = 14.08672917417959` So `is_mm_compute_bound` returns `False` and `_should_pad_bench` exits with `False`.

So we get this failure due to no cache entries:
```
  File "/pytorch-v2.9.0/test/inductor/test_pad_mm.py", line 435, in test_exclude_padding
    self.assertTrue(len(local_cache) == 2)
AssertionError: False is not true
```
BTW: Why is `assertTrue` used instead of `assertEqual`?

Change size to 61 which is bigger than 3x 14.1 and not a multiple of 4, requiring padding.

The number I choose was:
- 8.3 worked before
- 14.1 works now
- Extrapolate 1 step so it doesn't easily break again -> 19.9
- `arithmetic_intensity` must be bigger than that, i.e. `3*19.9 = 60`, and not a multiple of 4 to require padding at all -> 61

Pull Request resolved: https://github.com/pytorch/pytorch/pull/169177
Approved by: https://github.com/jansel