Revert "[Dynamo] Represent class.__dict__ as a MappingProxyVariable (#177807)"
This reverts commit d2b2ffb9614f04be8c20d6375a3b113607b0b8ca.

Reverted https://github.com/pytorch/pytorch/pull/177807 on behalf of https://github.com/georgehong due to Revert this stack due to observing first-time test breakages: FAILED CONSISTENTLY: test/test_multiprocessing_spawn.py::ParallelForkServerShouldWorkTest::test_terminate_signal -- torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__' ([comment](https://github.com/pytorch/pytorch/pull/176773#issuecomment-4128280508))