[FSDP] Fix _unshard() passing Stream instead of Event (#170525)
Pass self._unshard_event instead of self._unshard_stream to UnshardHandle, fixing AttributeError: 'Stream' object has no attribute 'wait'.

Fixes #168947

Pull Request resolved: https://github.com/pytorch/pytorch/pull/170525
Approved by: https://github.com/weifengpy