Revert "Accelerate SDPA on Arm CPUs: Unroll exp_sum and max_mul kernels (#177009)"
This reverts commit f98c2983932cf41aacfcf42691b5a77e5e484752.

Reverted https://github.com/pytorch/pytorch/pull/177009 on behalf of https://github.com/yangw-dev due to sorry it seems this breaks internal tests xplat/caffe2/aten/src/ATen/cpu/vec/vec128/vec128_convert.h:390:17: error: use of undeclared identifier 'convert_float_half', D96767295. please reach out to meta internal folks to resolve this ([comment](https://github.com/pytorch/pytorch/pull/177009#issuecomment-4077955167))