Fix torch.fx.symbolic_trace to_folder with torch.nn.Sequential (#169279)
Fixes #169276

## Summary

`torch.nn.Sequential` saves it's modules as numerical attribute entries (`"0", "1", ...`); however, when using `to_folder` it assumes that the entry is an alpha numerical entry which follows syntactically valid Python naming convention (from [here ](https://peps.python.org/pep-0008/#type-variable-names)); however, numerical entries do not follow that standard as such doing `self.0 = ...` is not a valid operation.

## Root Cause

```python
temp = Sequential(nn.Linear(10, 10), nn.Sigmoid())
graph = torch.fx.symbolic_trace(temp)
graph.to_folder("out_folder")
```

outputs a module with entries,

```python
import torch
from math import inf
from math import nan
NoneType = type(None)
import torch
from torch import device
import torch.fx._pytree as fx_pytree
import torch.utils._pytree as pytree

from torch.nn import *
class FxModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.0 = Linear(in_features=10, out_features=10, bias=True)
        self.1 = torch.load(r'out_folder/1.pt', weights_only=False) # Sigmoid()
        self.load_state_dict(torch.load(r'out_folder/state_dict.pt'))

    def forward(self, input):
        input_1 = input
        _0 = getattr(self, "0")(input_1);  input_1 = None
        _1 = getattr(self, "1")(_0);  _0 = None
        return _1
```

where clearly in Python you cannot have attributes directly set as `self.0` or `self.1` as such this would not compile

```python
  File "./out_folder/module.py", line 15
    self.0 = Linear(in_features=10, out_features=10, bias=True)
        ^^
SyntaxError: invalid syntax
```

## Fix
Instead of using the assignment operator (`self.{x} = y` ) when creating the module from `to_folder` we in instead use `setattr(self, '{x}', y)`, such that it guarantees that the attribute will be set as a string.

## Test Plan
Added `test_to_folder_class` and `test_to_folder_sequential`

`test_to_folder_class`: tests for a class that has a couple of edge cases where the `torch.nn.Module` has a `torch.nn.Sequential`, a parameter and a parameter named a number (0 in this case)
`test_to_folder_sequential`: tests specifically when the module input is a `torch.nn.Sequential` module

Pull Request resolved: https://github.com/pytorch/pytorch/pull/169279
Approved by: https://github.com/ezyang