Revert "[xpu][test] Port distributed checkpoint test cases on Intel GPU (#168921)"
This reverts commit 85ea6f4522cd3c736973bf34a3391807df1d12cd.

Reverted https://github.com/pytorch/pytorch/pull/168921 on behalf of https://github.com/yangw-dev due to sorry but seems like this break internal tests  dlrm/tests/amd:aps_dlrm_local_model_publish_test_on_amd due to AttributeError: partially initialized module 'triton' has no attribute 'language' (most likely due to a circular import)  ([comment](https://github.com/pytorch/pytorch/pull/168921#issuecomment-3755755311))