[FA3] pass max_q and max_k for varlen attn (#173681)
Fixes error below:

```
    File "/home/liangel/local/pytorch/torch/nn/attention/_fa3.py", line 417, in _fa3_flash_attention_forward_impl
      out, lse = _fa3_run_forward(
                 ^^^^^^^^^^^^^^^^^
    File "/home/liangel/local/pytorch/torch/nn/attention/_fa3.py", line 282, in _fa3_run_forward
      out, softmax_lse, out_accum, softmax_lse_accum = _FA3_CUDA_FWD(
                                                       ^^^^^^^^^^^^^^
    File "/home/liangel/local/pytorch/torch/_ops.py", line 1258, in __call__
      return self._op(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    RuntimeError: mha_fwd, /pytorch/third_party/flash-attention/hopper/flash_api_stable.cpp:814,
                           max_seqlen_q must be provided if cu_seqlens_q is provided
```

`_fa3_flash_attention_forward_impl` has `max_q` and `max_k` params passed in from `varlen_attn` so we should continue passing these down to the kernel call.

Tests:
added basic functionality test for varlen to `test_fa3.py`. correctness tests can stay in `test_varlen_attention.py`.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/173681
Approved by: https://github.com/drisspg, https://github.com/howardzhang-cv