Revert "dist: add list_keys to Store API (#167883)"
This reverts commit b0cd006c1426b8b47b2e2544b384c4d336847b9d.

Reverted https://github.com/pytorch/pytorch/pull/167883 on behalf of https://github.com/yangw-dev due to break some internal test,  error: use of undeclared identifier, reached out author but no resp, so revert this to keep diff train hygiene ([comment](https://github.com/pytorch/pytorch/pull/167883#issuecomment-3555212038))