[TorchRec] mark `torch._utils_internal.justknobs_check` as constant in dynamo (#174149)
Summary:
X-link: https://github.com/meta-pytorch/torchrec/pull/3713

# context
* **justknobs** is supported in pytorch via this API: `torch._utils_internal.justknobs_check`
* naturally TorchRec is using this torch-native API for killswitch impl: https://fb.workplace.com/groups/429376538334034/permalink/1343336826937996/
* A recent killswitch use case in TorchRec causes a graph break in PT2 compilation, which indicates **justknobs is incompatible with torch.compile**
* The workaround (D91704824) is to wrap the justknobs_check with `torch._dynamo.assume_constant_result` in TorchRec
* Somehow this workaround breaks the torch.package backward compatibility, and is reverted in D91941786
* This diff merges the `assume_constant_result` [decorator](https://www.internalfb.com/code/fbsource/[ca61d3e38b16d1a3022ee295357682a46301f9be]/fbcode/caffe2/torch/_dynamo/decorators.py?lines=170) inside the [justknobs_check](https://www.internalfb.com/code/fbsource/[df1ec41e9a97d4342c1bb8edc13b269f284302b3]/fbcode/caffe2/fb/_utils_internal.py?lines=539), we believe this approach is more generic since the `justknobs_check` is PT2-incompatible and should be marked as `assume_constant_result` all the time.
* more context about model processing torch compatibility: [Runbook](https://docs.google.com/document/d/17d5ZEmawaQEv6pqyqkblqOhM7QUW8km7ROratverl5Y)
* https://fb.workplace.com/groups/1075192433118967/permalink/1869680110336858/

Test Plan:
* run command
```
buck test fbcode//aiplatform/modelstore/model_generation/pipeline/transforms/compat_tests:distributed_inference_transform_compat_tests
```

Buck UI: https://www.internalfb.com/buck2/3430ac0d-9768-4841-95b4-1617cbf2db80
Test UI: https://www.internalfb.com/intern/testinfra/testrun/2533275137889226

* run pt2 test
```
buck test fbcode//mode/opt fbcode//torchrec/distributed/tests:test_pt2 -- test_justknobs_check
```

Buck UI: https://www.internalfb.com/buck2/9f9f9983-65e2-4cdc-a263-f0a9ee0b2883
Test UI: https://www.internalfb.com/intern/testinfra/testrun/16607023770439765

* baseline (expected failure)
```
======================================================================
ERROR: test_justknobs_check (torchrec.distributed.tests.test_pt2.TestPt2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/f1955037d3bc1b4b/torchrec/distributed/tests/__test_pt2__/test_pt2#link-tree/torchrec/distributed/tests/test_pt2.py", line 1010, in test_justknobs_check
    compiled_out = compiled_fn(x, y)
  File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/f1955037d3bc1b4b/torchrec/distributed/tests/__test_pt2__/test_pt2#link-tree/torch/_dynamo/eval_frame.py", line 1002, in compile_wrapper
    raise e.with_traceback(None) from e.__cause__  # User compiler error
torch._dynamo.exc.Unsupported: Attempted to call function marked as skipped
  Explanation: Dynamo developers have intentionally marked that the function `justknobs_check` in file `/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/f1955037d3bc1b4b/torchrec/distributed/tests/__test_pt2__/test_pt2#link-tree/torch/_utils_internal.py` should not be traced.
  Hint: Avoid calling the function `justknobs_check`.
  Hint: Apply `torch._dynamo.dont_skip_tracing` to the function `justknobs_check` to force tracing into the function. More graph breaks may occur as a result of attempting to trace into the function.
  Hint: Please file an issue to PyTorch.

  Developer debug context: module: torch._utils_internal, qualname: justknobs_check, skip reason: <missing reason>

 For more details about this graph break, please visit: https://meta-pytorch.github.io/compile-graph-break-site/gb/gb0007.html

from user code:
   File "/data/users/hhy/fbsource/buck-out/v2/gen/fbcode/f1955037d3bc1b4b/torchrec/distributed/tests/__test_pt2__/test_pt2#link-tree/torchrec/distributed/tests/test_pt2.py", line 1001, in fn
    if torch._utils_internal.justknobs_check("test", True):

Set TORCHDYNAMO_VERBOSE=1 for the internal stack trace (please do this especially if you're reporting a bug to PyTorch). For even more developer context, set TORCH_LOGS="+dynamo"

----------------------------------------------------------------------
Ran 1 test in 0.343s
```
Buck UI: https://www.internalfb.com/buck2/c2a663ad-6b4b-4f6b-b276-f77d064b871a
Test UI: https://www.internalfb.com/intern/testinfra/testrun/11258999214943965

Differential Revision: D91653482

Pull Request resolved: https://github.com/pytorch/pytorch/pull/174149
Approved by: https://github.com/williamwen42