Disable `fa4` on SM 12.0 in `test_varlen_attention` (#178567)
Following https://github.com/pytorch/pytorch/blob/a3568ea3/torch/nn/attention/_fa4.py#L110-L111
```
RuntimeError: FA4 flash_attention forward unsupported: FA4 requires compute capability 9.0 or 10.0
```

Pull Request resolved: https://github.com/pytorch/pytorch/pull/178567
Approved by: https://github.com/drisspg, https://github.com/liangel-02