Revert "Remove TorchVitals (#178479)"
This reverts commit 321eb8662a4667179eb6821c40ad84ec9ebd0c4b.

Reverted https://github.com/pytorch/pytorch/pull/178479 on behalf of https://github.com/georgehong due to change is breaking internal tests: AttributeError: module 'torch' has no attribute 'set_vital' ([comment](https://github.com/pytorch/pytorch/pull/178479#issuecomment-4145885127))