[test] Pass a tuple of 2 `SwizzleType` to nvfp4 `scaled_mm_v2` with two scales (#177625)
According to
https://github.com/pytorch/pytorch/blob/38e58d771bc81356c9c2c3f64490e8883328d852/aten/src/ATen/native/cuda/ScaledBlas.cpp#L1236-L1242, both `swizzle_a` and `swizzle_b` should be a tuple of 2 `SwizzleType`.

Currently, 4th input causes some relevant tests such as `TestDecompCUDA.test_comprehensive_torch__scaled_mm_v2_cuda_float8_e4m3fn` and `TestCommonCUDA.test_out_warning_torch__scaled_mm_v2_cuda` to fail:
```
ValueError: swizzle_a must have 2 values, got 1
Exception raised from check_swizzle_lengths at /path/to/pytorch/aten/src/ATen/native/cuda/ScaledBlas.cpp:1252

Caused by sample input at index 4:
SampleInput(input=Tensor[size=(256, 256), device="cuda:0", dtype=torch.float4_e2m1fn_x2],
  args=(
    Tensor[size=(256, 768), dtype=torch.float4_e2m1fn_x2, contiguous=False],
    TensorList[Tensor[size=(256, 32), dtype=torch.float8_e4m3fn], Tensor[size=(1,), dtype=torch.float32]],
    (<_ScalingType.BlockWise1x16: 2>, <_ScalingType.TensorWise: 0>),
    (<_SwizzleType.SWIZZLE_32_4_4: 1>),   # <-- only 1 value, kernel expects 2
    ...
  )
)
```
Pull Request resolved: https://github.com/pytorch/pytorch/pull/177625
Approved by: https://github.com/slayton58