Revert "Disable TD for the cpython tests (#178185)"
This reverts commit 585b45521e70daf9859c88ec384148dc2d4eeb08.

Reverted https://github.com/pytorch/pytorch/pull/178185 on behalf of https://github.com/georgehong due to Revert this stack due to observing first-time test breakages: FAILED CONSISTENTLY: test/test_multiprocessing_spawn.py::ParallelForkServerShouldWorkTest::test_terminate_signal -- torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__' ([comment](https://github.com/pytorch/pytorch/pull/176773#issuecomment-4128280508))