Revert "Add CPython test case `test_descr` (#176773)"
This reverts commit 083eae6fd9204cda763c56dea0dca93e7636ee04.

Reverted https://github.com/pytorch/pytorch/pull/176773 on behalf of https://github.com/georgehong due to Revert this stack due to observing first-time test breakages: FAILED CONSISTENTLY: test/test_multiprocessing_spawn.py::ParallelForkServerShouldWorkTest::test_terminate_signal -- torch._dynamo.exc.InternalTorchDynamoError: AttributeError: 'method' object has no attribute '__dict__' ([comment](https://github.com/pytorch/pytorch/pull/176773#issuecomment-4128280508))